Add cache-control header to uploaded files on S3
tlatsas/webpacker_uploader pull request #16
Opened 2021-11-18 14:19 UTC by Dimitris24sta23

@tlatsas Hey there!

We need to add a cache-control header in uploaded files in S3
I've added an option and seems to work.

Is it easy for you to review it?

Thanks!

2021-11-21 17:34 UTC, tlatsas requested changes
Hello @Dimitris24sta23, thanks for the PR! I think it makes sense to add this.

The configuration object `WebpackerUploader::Configuration` is used for holding more global and gem-related configuation options, affecting how this gem works.

Whereas the cache control option is more closely tied to the bucket / uploaded files. Having said that I think it is best to add the cache control option as an option to the `upload!` method.

This is very similar to how the `prefix` is set in the same method. That way we can pass bucket or file-related options there and keep the gem configuration to a bare mininum.

Can you please update the PR to reflect this? You need to remove the option added to the configuration object and add a new parameter named `cache_control` to the `upload!` method in `instance.rb` file. In the readme file add a new section similar to the one [describing the prefix](https://github.com/tlatsas/webpacker_uploader#prefix-remote-files).

2021-11-21 17:34 UTC, tlatsas commented on test/test_helper.rb
> +    def upload!(object_key, file, content_type = "", cache_control)
I would sugget providing a default value here as well.

2021-11-23 08:13 UTC, tlatsas reviewed
Looks good overall! A few more small changes here and there and we can merge this!

I think I can merge and release a new version later today if you send these changes. 🙏

2021-11-23 08:13 UTC, tlatsas commented on test/webpacker_uploader_test.rb
> +    puts @asset_objects
You can remove this `puts` from the test.

2021-11-23 09:32 UTC, Dimitris24sta23 commented on lib/webpacker_uploader/version.rb
> +  VERSION = "0.7.0"
@tlatsas Sorry did this cause i was loading this gem directly from my gitgub to test it.

2021-11-23 14:03 UTC, tlatsas approved these changes
LGTM, thanks for the PR! 🎉

2021-11-23 14:04 UTC, merged